version: '3'

services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: 0000
  
  
  

  frontend:
    image: node:14
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: npm run serve
    ports:
      - "8080:8080"
